FROM node@sha256:6c74791e557ce11fc957704f6d4fe134a7bc8d6f5ca4403205b2966bd488f6b3
RUN apt-get update && apt-get install -y --no-install-recommends gcc=4:12.2.0-3 libc6-dev=2.36-9+deb12u14 && rm -rf /var/lib/apt/lists/*
COPY probe.c /probe.c
RUN cc -shared -fPIC -I/usr/local/include/node /probe.c -o /probe.node
